# Loading Tests

In [55]:
from importlib import reload
from src.main import mechanical_computations, classes, geometry_utilities
from src.tests import helper_functions, test_cable_roads, test_geometry, test_mechanical_computations

In [68]:
reload(helper_functions)
reload(classes)
line_gdf, tree_gdf, height_gdf = helper_functions.set_up_gdfs()

In [69]:
reload(classes)
cable_road = classes.load_cable_road(line_gdf, 0)
print(cable_road.b_length_whole_section)
print(cable_road.c_rope_length)

122.2226439780678
141.90789913091348


In [62]:
cr = classes.initialize_cable_road_with_supports(cable_road.line, height_gdf, 80000)

Cable road created from line:  (-22.809794172088516, -5.018566541428784) to  (-107.9110969, 82.70909714)


In [5]:
reload(test_cable_roads)
test_cable_roads.test_supported_cable_road_parameters(line_gdf, height_gdf, line_gdf.iloc[0])

checking if no collisions overall line
checking if tower and anchor trees hold
found anchor tree that holds
checking if support withstands tension
forces on lr support 5067.325978612784 4513.24959442041
checking if support withstands tension
forces on lr support 5067.325978612784 4513.24959442041
checking if no collisions overall line
checking if no collisions overall line


In [8]:
test_cable_roads.test_unsupported_cable_road_parameters(line_gdf, height_gdf)

checking if no collisions overall line


In [11]:
test_cable_roads.test_cable_road_creation(line_gdf, height_gdf)

Cable road created from line:  (-22.809794172088516, -5.018566541428784) to  (-107.9110969, 82.70909714)
Tension to begin with is 85000.0
checking if tower and anchor trees hold
did not find anchor tree that holds - iterating
did not find anchor tree that holds - iterating
did not find anchor tree that holds - iterating
Tower and anchors hold: False
checking if tower and anchor trees hold
did not find anchor tree that holds - iterating
did not find anchor tree that holds - iterating
did not find anchor tree that holds - iterating
Tower and anchors hold: False
checking if tower and anchor trees hold
did not find anchor tree that holds - iterating
did not find anchor tree that holds - iterating
did not find anchor tree that holds - iterating
Tower and anchors hold: False
checking if tower and anchor trees hold
found anchor tree that holds
Tower and anchors hold: True
After the iterative process it is now 55000.0
checking if no collisions overall line
Found collisions
Need to find support

In [16]:
reload(test_geometry)
test_geometry.test_cr_feasability()

checking if tower and anchor trees hold
found anchor tree that holds


In [21]:
reload(test_mechanical_computations)

test_mechanical_computations.test_check_if_no_collisions_cable_road(line_gdf)
test_mechanical_computations.test_check_if_support_withstands_tension(line_gdf)
test_mechanical_computations.test_xz_line_from_cr_startpoint_to_centroid(line_gdf)
test_mechanical_computations.test_compute_resulting_force_on_cable()

checking if no collisions overall line
checking if no collisions overall line


In [241]:
reload(test_geometry)
reload(geometry_utilities)
test_geometry.test_rotation()
# test_geometry.test_3d_line_rotate()

AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0.1

Mismatched elements: 2 / 3 (66.7%)
Max absolute difference: 0.3
Max relative difference: 1.
 x: array([0., 0., 1.])
 y: array([0.3, 0.3, 0.9])

In [247]:
a = geometry_utilities.rotate_3d_point_in_z_direction(classes.Point_3D(10, 10, 10), 20)
a.xyz

array([10.20085637, 10.20085637,  9.58566945])

In [257]:
np.cos(np.deg2rad(0))

1.0

In [228]:
import math
# take our original vector and normalize it
vec = np.array([10,10,10])
old_vec = vec
old_norm = np.linalg.norm(vec)
# norm = np.linalg.norm(vec)
# vec = vec / norm
# calculate the z angle and transform our last value
a = math.cos(np.deg2rad(10))
vec[-1] = vec[-1]*a
norm = np.linalg.norm(vec)

old_vec= old_vec * norm
old_vec
# normalize the vector again to 
# vec = vec / np.linalg.norm(vec)
# 
# vec = vec * norm
vec

array([10, 10,  9])

In [232]:
(old_norm/norm)*vec

array([10.33254885, 10.33254885,  9.29929397])

In [239]:
original_vector = np.array([20,10,10])
original_norm = np.linalg.norm(original_vector)

# calculate the z angle transformation
a = math.cos(np.deg2rad(45))
new_vector = np.array([original_vector[0], original_vector[1], original_vector[2]*a])

# get the ratio of the original norm to the new norm and multiply the new vector with it
new_norm = np.linalg.norm(new_vector)
ratio = original_norm/new_norm
new_vector = new_vector * ratio
new_vector


array([20.88931871, 10.44465936,  7.38548946])