# Loading Tests

In [5]:
from importlib import reload
from src.main import mechanical_computations, classes, geometry_utilities, cable_road_computation
from src.tests import helper_functions, test_cable_roads, test_geometry, test_mechanical_computations

In [46]:
line_gdf, tree_gdf, height_gdf = helper_functions.set_up_gdfs()

2

In [48]:
cable_road = classes.load_cable_road(line_gdf, 2)
cable_road.count_segments()

0

In [8]:
test_cable_roads.test_supported_cable_road_parameters(line_gdf, height_gdf, line_gdf.iloc[0])
test_cable_roads.test_unsupported_cable_road_parameters(line_gdf, height_gdf)
test_cable_roads.test_cable_road_creation(line_gdf, height_gdf)
test_cable_roads.test_raise_height_and_check_tension(cable_road)

checking if no collisions overall line
Cable road created from line:  (-22.809794172088516, -5.018566541428784) to  (-107.9110969, 82.70909714)
Tension to begin with is 85000.0
checking if tower and anchor trees hold
exerted force 85000.0
did not find anchor tree that holds - iterating
exerted force 85000.0
did not find anchor tree that holds - iterating
exerted force 85000.0
did not find anchor tree that holds - iterating
Tower and anchors hold: False
checking if tower and anchor trees hold
exerted force 75000.0
did not find anchor tree that holds - iterating
exerted force 75000.0
did not find anchor tree that holds - iterating
exerted force 75000.0
did not find anchor tree that holds - iterating
Tower and anchors hold: False
checking if tower and anchor trees hold
exerted force 65000.0
did not find anchor tree that holds - iterating
exerted force 65000.0
did not find anchor tree that holds - iterating
exerted force 65000.0
did not find anchor tree that holds - iterating
Tower and anc

In [51]:
reload(test_cable_roads)
reload(classes)
cable_road = classes.load_cable_road(line_gdf, 0)
test_cable_roads.test_raise_tension_and_check_height(cable_road)

In [85]:
reload(test_mechanical_computations)
reload(mechanical_computations)
test_mechanical_computations.test_check_if_no_collisions_cable_road(line_gdf)
test_mechanical_computations.test_check_if_support_withstands_tension(line_gdf)
# test_mechanical_computations.test_xz_line_from_cr_startpoint_to_centroid(line_gdf) needs to be reworked for 3D
test_mechanical_computations.test_compute_resulting_force_on_cable()
# test_mechanical_computations.test_compute_tension_loaded_vs_unloaded_cableroad(cable_road) doesnt work - why is the tension so low?

checking if no collisions overall line
checking if no collisions overall line
checking if support withstands tension
Angle between lines 7.975870866838704
Angle between lines 6.897933645471483
forces on lr support 1554.7139293218052 1409.311350370052
checking if support withstands tension
Angle between lines 12.440100791930604
Angle between lines 9.722163561908644
forces on lr support 1641.2076240055937 1441.6988037038827


In [144]:
reload(test_geometry)
reload(geometry_utilities)
test_geometry.test_cr_parameter_feasability(cable_road,
        line_gdf,
        tree_gdf,
        height_gdf)
test_geometry.test_rotation()
test_geometry.test_3d_line_rotate()
test_geometry.test_angle_between_3d_lines()

checking if tower and anchor trees hold
exerted force 55000.0
found anchor tree that holds
[0 1 0]
[0 1 0]
[-1  1  0]


AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0.1

Mismatched elements: 3 / 3 (100%)
Max absolute difference: 0.70710678
Max relative difference: 0.1785113
 x: array([ 1.414214,  1.414214, -0.707107])
 y: array([1.2, 1.2, 0. ])

In [157]:
import numpy as np
reload(geometry_utilities)
point = geometry_utilities.rotate_3d_point_in_z_direction(classes.Point_3D(1, 0, 0), 90)
point.xyz

[-0.  1.  0.]


In [142]:
reload(geometry_utilities)
R = geometry_utilities.construct_rotation_matrix(45, [1, -1, 0])
point = np.array([1, 1, 1])
point_rotated = np.dot(R, point)
point_rotated

array([1.11022302e-16, 1.11022302e-16, 2.12132034e+00])